#!/bin/bash

d=/var/go/gocd-setup
[ -d "$d" ] || git clone https://github.com/genivigo/gocd-setup "$d"

set -e
cd "$d"
/usr/bin/git config user.name "Cron $HOSTNAME"
/usr/bin/git config user.email "noemail"
/usr/bin/git fetch
git reset origin/master --hard
/usr/bin/apt-get update
/usr/bin/apt-get install -y $(cat common_build_dependencies | egrep -v '^-')
# Packages prefixed with "-" will be removed
/usr/bin/apt-get remove -y $(cat common_build_dependencies | egrep '^-' | sed 's/^-//')
