#!/bin/bash -e

cd ~/gocd-setup
/usr/bin/git config user.name "Cron $HOSTNAME"
/usr/bin/git config user.email "noemail"
/usr/bin/git fetch
git reset origin/master --hard
/usr/bin/apt-get install -y $(cat common_build_dependencies)
