#!/bin/sh -x

# Just a helper script, you can probably ignore this

#img=phusion/baseimage
img=gotest_java

# Kill and re-run container
docker rm -f gotest 2>&1
docker run -ti --detach -v $PWD:/gocd-setup --name gotest $img /bin/bash 

# Copy scripts into container for testing
tar cf - --exclude='*.rpm' * | docker exec -i gotest tar xvf -

echo "Hit return to attach" ; read
docker attach gotest
